FROM maven:3.8.6-openjdk-8-slim

COPY settings.xml /usr/share/maven/ref/
COPY pom.xml /tmp/pom.xml
COPY src/ /tmp/src
RUN mvn -B -f /tmp/pom.xml -s /usr/share/maven/ref/settings.xml dependency:go-offline